version: "3.8"
services:

  db:
    container_name: db
    image: postgres:14.4
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: scraping
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"

  api:
    container_name: api
    build: ./api
    ports:
      - "8000:8000"
    volumes:
      - ./api:/api
    command: bash -c "wait-for-it --service db:5432 && alembic upgrade head && python run.py"

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - "5050:80"
    logging:
      driver: none

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.9-management
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    environment:
      - RABBITMQ_ERLANG_COOKIE=${RABBITMQ_ERLANG_COOKIE-secret_cookie}
    ports:
      - "5672:5672"
      - "15672:15672"
    hostname: rabbitmqhost
    logging:
      driver: none

  celery_worker:
    container_name: celery
    build: ./api
    volumes:
      - ./api:/api
    command: bash -c "wait-for-it --service api:8000 && celery -A celery_worker worker --loglevel=info -f celery.log -B"
    environment:
      - CELERY_BROKER_URL=${CELERY_BROKER_URL-amqp://guest:guest@rabbitmqhost:5672//}
      - CELERY_RESULT_BACKEND=${CELERY_RESULT_BACKEND-db+postgresql+psycopg2://postgres:password@db/scraping}

  flower:
    container_name: flower
    image: mher/flower:0.9.5
    ports:
      - "5566:5566"
    environment:
      - CELERY_BROKER_URL=${CELERY_BROKER_URL-amqp://guest:guest@rabbitmqhost:5672//}
      - CELERY_RESULT_BACKEND=${CELERY_RESULT_BACKEND-db+postgresql+psycopg2://postgres:password@db/scraping}
      - FLOWER_PORT=5566

volumes:
  db_data:
  pgadmin_data:
  rabbitmq_data: